Translate the 02.1
mingrammer/build-web-application-with-golang pull request #10
Opened 2017-03-06 15:09 UTC by mingrammer

2017-03-06 16:03 UTC, qkraudghgh requested changes

2017-03-06 16:03 UTC, qkraudghgh commented on ko/02.1.md
>      }
이거 마크다운으로 봤을때 이쁘게 해주세요
` ```java ` 이런걸 쓰고 or 분리하고

2017-03-06 16:03 UTC, qkraudghgh commented on ko/02.1.md
> +
` ```go `

이거 써주세요 코드 이쁘게나오게

2017-03-06 16:03 UTC, qkraudghgh commented on ko/02.1.md
>      }
이것두 마찬가지

2017-03-06 16:03 UTC, qkraudghgh commented on ko/02.1.md
>  - [Directory](preface.md)
목차로 바꿔줘요

2017-03-07 02:34 UTC, qkraudghgh requested changes

2017-03-07 02:34 UTC, qkraudghgh commented on ko/02.1.md
> +Go 프로그래밍 언어는 대규모 팀에서 대규모 유저를 위한 확장 가능한 웹 애플리케이션을 개발할 수 있도록 하는 한 가지 목표를 염두에 두고 만들어졌습니다. 이게 Go 언어를 가능한 표준화할 수 있게끔 만든 이유이며, 이 때문에 `gofmt` 도구와 개발자간의 파벌이 생기지 않도록 하는 엄격한 가이드라인이 생겼습니다. 다른 언어에서는 열린 괄호를 어디에 두
다른 언어에서는 열린 괄호를 어디에 두어야하는지에 대한 거의 종교적인 싸움까지 일어납니다. ->
다른 언어에서는 열린 괄호를 어디에 두어야하는지에 대한 거의 종교적인 싸움이 일어나기도 합니다.

2017-03-07 02:34 UTC, qkraudghgh commented on ko/02.1.md
> +이는 표면적으로는 별거 아닌 문제처럼 보일 수 있지만, 코드베이스가 커지고 같은 코드베이스에 더 많은 사람들이 함께 작업하게 되면, 코드를 아름답게 유지하기가 어렵습니다. 여러분이 파이썬을 알고 있다면, 아마 훌륭한 코드를 짜기위한 가이드라인인 PEP8을 알겁니다. 우리는 현재 로봇이 자동차를 운전하는 시대에 살고 있습니다. 따라서 우리는 코드를 그냥 작
아마 훌륭한 코드를 짜기위한 가이드라인인 PEP8을 알겁니다. ->
훌륭한 코드를 짜기위한 가이드라인인 PEP8을 아마 알고 있을 겁니다.
맞춤법을 모르겠네

2017-03-07 02:34 UTC, qkraudghgh commented on ko/02.1.md
> +구글은 현재 사용하고 있는 도구들로부터 마주한 모든 문제들을 완화시키기 위해, 여러분이 배우고자하는 Go라는 시스템 언어를 개발했습니다. Go 언어를 사용하면 얻을 수 있는 많은 장점들이 있으며 모든 동전이 양면을 가지듯 단점 또한 있습니다. 하지만 코드 포맷을 지정하는 방법에 대한 싸움이 일어나지 않도록 설계한 언어이기 때문에 코드 포맷팅과 같은 부분에
누군가가 만든 gocode는 이와 정확히 동일합니다 ->
gocode는  전세계의 누군가가 작성하더라도 포맷이 정확히 동일합니다.

2017-03-07 02:34 UTC, qkraudghgh commented on ko/02.1.md
> +여기서 주목해야할 것은 Go에선 명령문 뒤에 세미콜론을 사용하지 않는다는건데, 글쎄, 그렇긴한데, 여기엔 사소하게 짚고가야할게  있습니다. 프로그래머는 세미콜론을 넣지 않지만, 컴파일러가 코드를 컴파일 할 때 Go 코드에 세미콜론을 추가합니다. 그렇기 때문에 다음 코드는 구문 오류입니다.
여기서 주목해야할 것은 Go에선 명령문 뒤에 세미콜론을 사용하지 않는다는건데, 글쎄, 그렇긴한데, 여기엔 사소하게 짚고가야할게  있습니다. -> 
여기서 주목해야할 것은 Go에선 명령문 뒤에 세미콜론을 사용하지 않는다는건데, 여기엔 사소하게 짚고가야할게  있습니다.

2017-03-07 04:02 UTC, mingrammer commented
@qkraudghgh Check it plz

2017-03-07 06:12 UTC, qkraudghgh approved these changes

2017-03-07 06:12 UTC, merged