Translate the 02.4
mingrammer/build-web-application-with-golang pull request #11
Opened 2017-03-07 07:47 UTC by qkraudghgh

2017-03-16 00:35 UTC, mingrammer requested changes

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +다른 프로그래밍 언어와 마찬가지로 Go에서 다른 속성이나 필드의 컨테이너 타입을 새로 정의 할 수 있습니다. 예를 들어 필드 이름과 나이를 가진 `person`이라는 유형을 작성하여 사람을 나타낼 수 있습니다. 이런 종류의 타입을 `struct`라고 부릅니다.
필드 이름과 나이를 가진 `person`이라는 유형을 작성하여 사람을 나타낼 수 있습니다. > 사람을 나타내기 위해 이름과 나이 필드를 가진 `person`이라는 타입을 정의할 수 있습니다.

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +구조체를 정의하는 세 가지 방법이 더 있습니다.
이거 문맥상 '정의' 보단 '초기화'인 것 같은데 흠

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +- 구조체를 순서없이 초기화하려면 `field : value` 형식을 사용합니다.
`field : value` > `field:value`

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +    Human  // 내장 필드는 Student 구조체가 Human이 가진 모든 필드를 포함한다는 것을 의미합니다.
내장 필드 > 임베딩 필드

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +    // student를 선언합니다.
student를 초기화합니다.

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +    // 몸무게를 변합니다.
변합니다 > 변경합니다

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +Figure 2.7 임베딩 Student와 Human
Student에서의 임베딩과 Human

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +위의 예제에서 우리는 모든 타입이 임베딩 필드로 쓰일 수 있고 함수를 사용하여 필드를 조작 할 수 있다는 것을 알 수 있었습니다.
필드를 조작 할 수 있다는 것을 알 수 있었습니다. > 필드를 조작 할 수 있다는 것을 볼 수 있었습니다.

2017-03-16 00:35 UTC, mingrammer commented on ko/02.4.md
> +    // Human에 있는 Phone 필드에 접근합니다.
Phone > phone

2017-03-18 07:04 UTC, qkraudghgh commented
@mingrammer 
check this plz

2018-03-25 07:29 UTC, mingrammer approved these changes

2018-03-25 07:30 UTC, merged