Translate the 02.8
mingrammer/build-web-application-with-golang pull request #13
Opened 2017-03-09 07:02 UTC by qkraudghgh

2017-03-11 12:06 UTC, mingrammer requested changes

2017-03-11 12:06 UTC, mingrammer commented on ko/02.8.md
> +- `func`는 함수와 메쏘드를 정의할 때 사용합니다.
메쏘드 > 메서드

method는 메서드로 통일

2017-03-11 12:06 UTC, mingrammer commented on ko/02.8.md
> +- `return`은 함수나 메쏘드에서 값을 반환할 때 사용합니다.
메쏘드 > 메서드

2017-03-14 08:41 UTC, qkraudghgh commented
@mingrammer 
check it plz

2017-03-15 03:54 UTC, mingrammer approved these changes

2017-03-15 03:54 UTC, merged