Translate the 02.3
mingrammer/build-web-application-with-golang pull request #14
Opened 2017-03-10 08:50 UTC by mingrammer

2017-03-11 11:29 UTC, qkraudghgh requested changes
주석 하나도 번역 안했던데 해주세요~

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// initialize x, then check if x greater than
주석 번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// the following code will not compile
주석 번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +`for`는 Go에서 가장 강력한 제어 로직입니다. 이는 `white`과 같이 루프에서 데이터를 읽고 반복적으로 연산을 수행할 수 있습니다.
white 오타 ㅋㅋ

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +예제는 말보다 유용합니다.
예제는 말보다 유용합니다. -> 말로하는 것보다 예제를 한 번 살펴보겠습니다.

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// Print：sum is equal to 45
주석 번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +종종 다중 할당이 필요한 경우가 있는데, Go는 `,` 연산자가 없기 때문에, `i, j = i +1, j - 1`와 같이 병렬 할당을 할 수 있습니다.
스페이스 써주세요 i + 1

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +    	break // or continue
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// continue prints 10、9、8、7、6、4、3、2、1
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +```go
이건 출력이니까 ``` go 안해도될듯?

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +	// multi-value return
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// return greater value between a and b
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +	max_xz := max(x, z) // call function max(x, z)
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +	fmt.Printf("max(%d, %d) = %d\n", y, z, max(y,z)) // call function here
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// return results of A + B and A * B
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +제가하는 말을 증명하기 위해 하나의 예를 들어보겠습니다.
제가 하는 말을

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// simple function to add 1 to a
이 아래로 쭉 번역해주세요 주석

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +봤습니까? `x`를 사용하는 `add1`을 호출했지만, `x`의 원래값은 변하지 않습니다.
봤습니까? -> 보셨나요?

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// simple function to add 1 to a
주석 번역 해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +type testInt func(int) bool // define a function type of variable
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +// pass the function `f` as an argument to another function
번역해주세요

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +### Panin과 Recover
Panic 오타

2017-03-11 11:29 UTC, qkraudghgh commented on ko/02.3.md
> +	f() // if f causes panic, it will recover
번역해주세요

2017-03-11 12:03 UTC, mingrammer commented
@qkraudghgh Check it plz

2017-03-14 08:38 UTC, qkraudghgh approved these changes

2017-03-14 08:38 UTC, merged