Translate 01.2
mingrammer/build-web-application-with-golang pull request #4
Opened 2017-03-03 01:47 UTC by qkraudghgh

2017-03-03 02:02 UTC, qkraudghgh commented
@mingrammer 
Check this plz

2017-03-04 04:39 UTC, mingrammer requested changes

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
하나 이상의 경로 (작업 공간)을 > 하나 이상의 경로 (작업 공간)를

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. > 이 때, `go get`은 내용을 $GOPATH의 첫번째 경로에 저장합니다.

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
당신 > 여러분

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
그러니 부디 규칙을 따르세요 규칙이 만들어졌을땐 다 이유가 있습니다. > 그러니 부디 규칙을 따르세요. 규칙이 만들어진데에는 다 이유가 있습니다.

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
$GOPATH안에 > $GOPATH 안에

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
$GOPATH안에 폴더를 생성하면 작성자가 당신의 프로젝트를 참조하는 패키지를 직접 설치하면 패키지를 가져 오는 모든 응용 프로그램이 중단됩니다. 왜냐면 `go get`이 패키지를 어디에서도 찾을 수 없기 때문입니다. > $GOPATH에 폴더를 만들때 패키지를 \<packagename\> 와 같이 직접 참조하기 때문에 코드를 변경하고자 하는 모든걸 할 수 없으며, 여러분의 패키지를 임포트하는 모든 애플리케이션이 중단됩니다. 왜냐하면 `go get`이 패키지를 그 어디에서도 찾을 수 없기 때문입니다.

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +패키지를 생성 할 때마다 `src` 폴더에 새로운 폴더를 생성해야하는데, 꼭 만들어야하는 main을 제외하고 `main` 폴더를 만드는 것은 선택 사항입니다. 폴더 이름은 일반적으로 사용할 패키지와 같습니다. 원하는 경우 계층구조를 지닌 폴더를 만들 수 있습니다. 예를 들어 `$GOPATH/src/github.com/astaxie/beedb` 디렉토리를
생성 할 때마다 > 생성할 때마다

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +우리는 이미 위에서 패키지를 만들었습니다. 하지만 어떻게 우리는 연습 목적으로 컴파일을 할 수 있을까요? 여기에 두가지 방법이 있습니다.
우리는 이미 위에서 패키지를 만들었습니다. 하지만 어떻게 우리는 연습 목적으로 컴파일을 할 수 있을까요? > 우리는 위에서 이미 패키지를 만들었지만, 이를 실용적인 목적으로 컴파일을 할 수 있는 방법은 무엇일까요?

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +이 애플리케이션을 컴파일 하려면 여러분은 `$GOPATH/src/mathapp` 폴더로 이동한 다음 `go install` 명령어를 실행해야합니다. 이제 `$GOPATH/bin/` 폴더에 `mathapp`이라는 실행 파일이 생성 된 것을 볼 수 있습니다. `./mathapp` 명령어를 이용해서 이 프로그램을 실행할 수 있고 실행 후 여러분에 터미널에서 아
생성 된 것을 > 생성된 것을

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +이 애플리케이션을 컴파일 하려면 여러분은 `$GOPATH/src/mathapp` 폴더로 이동한 다음 `go install` 명령어를 실행해야합니다. 이제 `$GOPATH/bin/` 폴더에 `mathapp`이라는 실행 파일이 생성 된 것을 볼 수 있습니다. `./mathapp` 명령어를 이용해서 이 프로그램을 실행할 수 있고 실행 후 여러분에 터미널에서 아
여러분에 > 여러분의

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +Go는 원격 패키지를 설치하기위한 `go get`이라는 도구를 가지고 있습니다. Github, Google Code, BitBucket 및 Launchpad를 포함한 대부분의 오픈 소스 커뮤니티를 지원합니다.
도구? 툴? 다른곳에선 툴로 통일해서 쓰긴했는데

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +사실, `go get`은 로컬 `$GOPATH/src`에 소스 코드를 복제하고 `go install` 명령어를 실행합니다.
`go get`은 로컬 `$GOPATH/src`에 소스 코드를 > `go get`은 로컬 파일 시스템의 `$GOPATH/src`에 소스 코드를

2017-03-04 04:39 UTC, mingrammer commented on ko/01.2.md
> +(윈도우 사용자일경우 환경 변수 형식이 `%GOPATH%`이지만, 이 책은 주로 Unix 계열을 따르므로 윈도우 사용자는 자신에게 맞게 고쳐 생각해야합니다.)
Windows의 환경 변수 포맷은 `%GOPATH%`이지만, 이 책은 주로 유닉스 스타일을 따르므로, Windows 유저는 이를 직접 바꿔야합니다.

2017-03-04 04:39 UTC, mingrammer commented on ko/code/readme.md
> +워크스페이스 문제들을 피하고 이 경로 내의 모든 폴더에서 개발할 수 있도록하려면,
있도록하려면 > 있도록 하려면

2017-03-04 04:39 UTC, mingrammer commented on ko/code/src/apps/ch.1.2/main.go
> +// 목적 :이 파일을 실행하여 작업 공간이 올바르게 설정되었는지 확인하기위함
목적 : > 목적:

2017-03-04 04:42 UTC, mingrammer requested changes

2017-03-04 04:42 UTC, mingrammer commented on ko/01.2.md
> +여러분은 `go get -u …`를 사용하여 원격 패키지를 업데이트 할 수 있으며, 모든 종속 패키지도 자동으로 설치할 수 있습니다.
여러분은 `go get -u …`를 사용하여 원격 패키지를 업데이트 할 수 있으며 > `go get -u …`를 사용하여 원격 패키지를 업데이트 할 수 있으며

여기선 여러분 빼도될듯

2017-03-04 04:42 UTC, qkraudghgh commented on ko/01.2.md
> +Go는 원격 패키지를 설치하기위한 `go get`이라는 도구를 가지고 있습니다. Github, Google Code, BitBucket 및 Launchpad를 포함한 대부분의 오픈 소스 커뮤니티를 지원합니다.
도구로 통일 ㄱㄱ

2017-03-04 11:26 UTC, qkraudghgh commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
첫번째 -> 첫 번째가 맞는 맞춤법입니다.

2017-03-04 11:29 UTC, qkraudghgh commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
$GOPATH에 폴더를 만들때 패키지를 <packagename> 와 같이 직접 참조하기 때문에 코드를 변경하고자 하는 모든걸 할 수 없으며, 여러분의 패키지를 임포트하는 모든 애플리케이션이 중단됩니다. 왜냐하면 go get이 패키지를 그 어디에서도 찾을 수 없기 때문입니다. 이 번역도 조금 이상한 것 같은데 어떻게 해야할까요

2017-03-04 11:34 UTC, qkraudghgh commented on ko/01.2.md
> +(윈도우 사용자일경우 환경 변수 형식이 `%GOPATH%`이지만, 이 책은 주로 Unix 계열을 따르므로 윈도우 사용자는 자신에게 맞게 고쳐 생각해야합니다.)
왠만하면 한글로 쓸 수 있는건 한글로 쓰는걸 선호합니다. 스타일 => 계열로 해도 이상이 없을 것 같네요
포맷 -> 형식 이것도 마찬가지구요 UNIX는 대명사라 그냥 영어를 차용했습니다.
윈도우도 영어로 바꿔야겠네요

2017-03-04 11:36 UTC, qkraudghgh commented on ko/01.2.md
> +(윈도우 사용자일경우 환경 변수 형식이 `%GOPATH%`이지만, 이 책은 주로 Unix 계열을 따르므로 윈도우 사용자는 자신에게 맞게 고쳐 생각해야합니다.)
유저 -> 사용자
도 마찬가지입니다.

2017-03-04 12:07 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로 (작업 공간)을 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때 `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장됩니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
규칙이 만들어졌을땐 다 이유가 있습니다. > 규칙이 만들어진데에는 다 이유가 있습니다.

과거형은 조금 어색

2017-03-04 12:13 UTC, mingrammer requested changes

2017-03-04 12:13 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로(작업 공간)를 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때, `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장합니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
규칙이 만들어졌을땐 다 이유가 있습니다. > 규칙이 만들어진데에는 다 이유가 있습니다.

과거형은 조금 어색

2017-03-04 12:13 UTC, mingrammer commented on ko/01.2.md
> +(Windows의 환경 변수 형식은 `%GOPATH%`이지만, 이 책은 주로 Unix 계열을 따르므로 Windows 사용자는 이를 직접 바꿔야합니다.)
`$GOPATH` 형식 자체는 유닉스 스타일의 형식이고 따라서 이 부분에서는 계열이 아니라 스타일이 더 알맞음. 계열이라고 하면 Unix-like랑 매칭됨

2017-03-04 12:13 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로(작업 공간)를 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때, `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장합니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
$GOPATH에 폴더를 만들때 패키지를 \<packagename\>과 같이 직접 참조하기 때문에 코드를 변경하는 모든 작업을 할 수가 없으며, 여러분의 패키지를 임포트하는 모든 애플리케이션이 중단됩니다. 왜냐하면 `go get`이 패키지를 그 어디에서도 찾을 수 없기 때문입니다.

2017-03-04 12:13 UTC, mingrammer commented on ko/01.2.md
> +$GOPATH에 하나 이상의 경로(작업 공간)를 가지는 것은 괜찮지만 `:`(윈도우에선 `;`)를 사용해서 경로를 나눠줘야 한다는 것을 기억하세요. 이때, `go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장합니다. 그래서 여러가지 버전을 같이 사용하지 않는 것이 좋습니다. 최악의 경우는 $GOPATH에서 프로젝트 이름으로 폴더를 생성
`go get`으로 저장한 내용들은 $GOPATH의 첫 번째 경로에 저장합니다. > `go get`이 저장한 내용들이 아니라 `go get` 명령어 자체가 받아온 내용들을 해당 경로에 저장하는 플로우이므로, "`go get`은 내용을 $GOPATH의 첫 번째 경로에 저장합니다." 또는 "`go get`은 $GOPATH의 첫 번째 경로에 내용을 저장합니다."가 더 자연스러움.

2017-03-04 12:22 UTC, mingrammer approved these changes
LGTM +1

2017-03-04 12:22 UTC, merged