Translate 01.4
mingrammer/build-web-application-with-golang pull request #6
Opened 2017-03-04 06:42 UTC by qkraudghgh

2017-03-04 12:00 UTC, qkraudghgh commented
@mingrammer 
`intelligent code completion`을 해석하는데 어려움이 있었습니다.
일단 `코드 자동완성`이라고 번역을 했는데 `Auto-completion`과 혼동되어 잘 번역을 못하겠네요 의견주세요

2017-03-06 07:04 UTC, mingrammer requested changes

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +# Go 개발자 도구
우리 이거 목차 포함해서 "개발 도구"로 바꿔야할듯. 왜 개발자 도구라 했었지 흐윽..

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +이번 장에서는, 코드 자동 완성 및 자동 포맷팅과 같은 기능을 사용하여보다 효율적인 프로그래밍이 가능하도록 도와주는 몇 가지 IDE를 보여 드리겠습니다. IDE는 모든 운영체제에서 동일하게 돌아가므로 여러분의 운영체제가 각각 다를지라도 아래에서 보여주는 내용과 차이가 별로 없어야합니다.
아래에서 보여주는 내용과 차이가 별로 없어야합니다. > 앞으로 보여줄 내용에 큰 차이는 없을겁니다.

가 더 자연스러울듯. Should를 ~합니다로 꼭 안해도 될 것 같음 여기선

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +- GO 언어 편집 지원
Go언어 편집 지원 > Go 소스 코드 에디터

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	- `F1`을 사용하여 코드 어드바이저 지원
~~ 사용한

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	- `F2`를 사용하여 함수 정의 보기
~ 사용한

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	- 다중 언어 지원
다중 언어 > 다국어

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	- 문서 편집기 테마 지원
텍스트 편집기 or 텍스트 에디터

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	- Kate를 사용하여 문법 보기 지원
Kate 기반 구문 강조 (Syntax Highlighting) 지원

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +- 코드 자동완성 기능
자동 완성

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	LiteIDE에서 `$GOPATH`를 보고 변경하는 것은 매우 쉽습니다. 이 값을 보고 변경하려면 `View - Setup GOPATH`를 따르세요.
보고 변경하는 것은 > 확인하고 변경하는 것은

이 더 자연스러울 것 같음

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +3. 설치가 성공했는지 확인하려면 Sublime을 연 다음 `main.go` 파일을 열어 적절한 구문 강조 표시가 있는지 확인하세요. 코드 자동완성을 확인해보려면 `import`를 입력해보세요. `import "fmt"`를 입력한 후, `import` 선언 다음에`fmt.`를 입력하여 함수에 대한 코드 자동 완성이 성공적으로 활성화되었는지 확인하세요.
적절한 구문 강조 표시가 있는지 확인하세요. > 구문 강조 표시가 제대로 되는지 확인하세요.

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +Vim은 프로그래머를 위해 널리 사용되는 텍스트 편집기로, 이전 버전인 Vi보다 발전했습니다.
Vim은 프로그래머를 위해 널리 사용되는 텍스트 편집기로, 이전 버전인 Vi보다 발전했습니다. > Vim은 프로그래머들에게 인기 있는 텍스트 편집기로, 이전 버전인 Vi의 발전형입니다. 이는 코드 자동 완성, 컴파일 및 에러 지점으로의 이동 등의 기능을 갖고있습니다.

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +vim-go 는 Vim의 오픈소스 플러그인으로 자동 완성, 컴파일, 에러지점으로 이동 등 Go 개발에 특화된 기능들이 있습니다.
vim-go는 광범위한 개발 환경 플러그인을 사용하는 Go 언어를 위한 vim의 오픈 소스 플러그인입니다.

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +Vim 플러그인은 [Pathogen](https://github.com/tpope/vim-pathogen) 그리고 [Vundle](https://github.com/VundleVim/Vundle.vim)로 관리되고 두개는 서로 다르게 동작합니다.
- Vim 플러그인 관리는 [Pathogen](https://github.com/tpope/vim-pathogen)과 [Vundle](https://github.com/VundleVim/Vundle.vim)가 주류입니다.
- 그러나 이 두 플러그인은 서로 다른 양상을 띕니다.
- Pathogen은 여러 디렉토리에 파일을 설치 한 후 각 플러그인을 관리하고 플러그인의 존재를 관리하지 못하게합니다. Vundle은 플러그인의 자동 검색 및 설치를 할 수 있게 해줍니다.

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	gocode 설정에대한 설명:
설정에 대한

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +	propose-builtins: 지능형 자동완성을 활성화 할지를 정합니다. 기본은 `false`입니다.
지능형 자동 완성의 활성 여부를 지정합니다. 기본값은 `false`입니다

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +Atom은 오픈소스이고 다중 플랫폼을 지원하는 멋진 텍스트 편집기로 Electron에 기반을두고있고 우리가 좋아하는 모든 편집기들을 기반으로합니다. Atom은 원하는대로 구성을 바꿀 수 있도록 설계되어 있지만 계속해서 기본 구성을 사용할 수도 있습니다.
기반을두고있고 > 기반을 두고 있고

2017-03-06 07:04 UTC, mingrammer commented on ko/01.4.md
> +Atom은 오픈소스이고 다중 플랫폼을 지원하는 멋진 텍스트 편집기로 Electron에 기반을두고있고 우리가 좋아하는 모든 편집기들을 기반으로합니다. Atom은 원하는대로 구성을 바꿀 수 있도록 설계되어 있지만 계속해서 기본 구성을 사용할 수도 있습니다.
우리가 좋아하는 모든 편집기들을 기반으로합니다. > 우리가 좋아하는 편집기들에 대한 모든것을 기반으로 합니다.

2017-03-06 09:56 UTC, qkraudghgh commented on ko/01.4.md
> +	- `F1`을 사용하여 코드 어드바이저 지원
음 그러면 코드 어드바이저가 F1을 사용한 것 처럼 보입니다

2017-03-06 10:44 UTC, mingrammer approved these changes
LGTM +1

2017-03-06 10:44 UTC, merged