Translate the 02.2
mingrammer/build-web-application-with-golang pull request #9
Opened 2017-03-06 14:50 UTC by qkraudghgh

2017-03-06 17:41 UTC, mingrammer requested changes

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +이번 장에서, Go 프로그래밍에서 상수, 기본 타입의 변수 정의하는 방법 및 몇가 기술을 알려 드리려고합니다.
이번 장에서는, 기본 타입의 상수와 변수를 정의하는 방법 및 Go 프로그래밍에서의 몇 가지 기술에 대해 알려드리려고 합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`var` 키워드는 변수를 정의하는 기본 형식입니다. Go는 변수 이름 뒤에 변수 타입 `type`을 넣습니다.
변수 이름 뒤에 변수 타입 `type`을 넣습니다. > 변수명 `뒤에` 변수 타입을 적습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// “variableName”과 타입을 함께 정의합니다.
이름이 "variableName"이고 타입이 "type"인 변수를 정의합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 3개의 변수를 타입과 함께 정의합니다.
타입이 "type"인 세 개의 변수를 정의합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +초기 값을 가진 변수를 정의하기
변수를 > 변수

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +초기 값을 가진 변수를 정의하기
초기 값 > 초기값

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +여러개의 변수를 초기 값과 함께 정의하기
초기 값 > 초기값

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +변수를 정의하는 것이 너무 지루하다고 생각하세요? 걱정마세요, 왜냐하면 Go 팀도 이 문제를 발견했기 때문입니다. 따라서 초기 값을 사용하여 변수 타입을 생략한체 변수를 정의할 수 있습니다. 코드는 다음과 같이 표시됩니다.
생략한체 > 생략한 채

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +변수를 정의하는 것이 너무 지루하다고 생각하세요? 걱정마세요, 왜냐하면 Go 팀도 이 문제를 발견했기 때문입니다. 따라서 초기 값을 사용하여 변수 타입을 생략한체 변수를 정의할 수 있습니다. 코드는 다음과 같이 표시됩니다.
초기 값 > 초기값

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +변수를 정의하는 것이 너무 지루하다고 생각하세요? 걱정마세요, 왜냐하면 Go 팀도 이 문제를 발견했기 때문입니다. 따라서 초기 값을 사용하여 변수 타입을 생략한체 변수를 정의할 수 있습니다. 코드는 다음과 같이 표시됩니다.
코드는 다음과 같이 표시됩니다. > 코드는 다음과 같이 쓸 수 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +타입을 정하지 않은 3개의 변수를 정의하고 그 값을 초기화합니다.
타입을 명시하지 않은 3개의 변수를 정의하고 ~

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +네, 여러분이 아직 만족할 수준으로 간단해지지 않았다는 것을 압니다. 우리가 이것을 어떻게 고치는지 다시 살펴봅시다.
아직도 충분히 간단하지 않다는걸 알고 있습니다. 이를 고치는 방법을 살펴봅시다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +타입을 정하지 않고 "var" 키워드도 없는 세개의 변수를 정의하고 그 값을 초기화합니다.
"var" 키워드를 사용하지 않고 타입을 명시하지 않은 세 개의 변수를 정의하고 그 값을 초기화합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`_`(공백)은 특별한 변수 이름입니다. 이것에 주어진 값은 무시됩니다. 예를 들어 `b`에 `35`를 주고 `34`를 버립니다.( ***이 예제는 단순히 어떻게 작동하는지 보여주기위해 작성하였습니다. 쓸데 없이 보일지 몰라도 함수의 반환값을 얻을 땐 종종 이 기호를 사용합니다.*** )
변수 이름 > 변수명

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`_`(공백)은 특별한 변수 이름입니다. 이것에 주어진 값은 무시됩니다. 예를 들어 `b`에 `35`를 주고 `34`를 버립니다.( ***이 예제는 단순히 어떻게 작동하는지 보여주기위해 작성하였습니다. 쓸데 없이 보일지 몰라도 함수의 반환값을 얻을 땐 종종 이 기호를 사용합니다.*** )
예를 들어 `b`에 `35`를 주고 `34`를 버립니다. > 예를 들어, 다음처럼 `35`는 `b`에 할당하고, `34`는 버립니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +프로그램에서 정의한 변수를 사용하지 않으면 컴파일러에서 컴파일 오류를 표시합니다. 다음 코드를 컴파일하고 무슨 일이 일어나는지 보세요.
컴파일 오류를 표시합니다. > 컴파일 오류를 발생시킵니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +## 상수(Constants)
상수 (Constants)

괄호 앞에 띄어쓰기 ㄱㄱ

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +상수는 컴파일시에 결정되는 값이며 런타임 중에 변경할 수 없습니다. Go에서는 숫자, 부울(boolean) 또는 문자열 타입을 상수로 사용할 수 있습니다.
런타임 중에 > 런타임중에 ?

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +### 부울(Boolean)
부울 (Boolean)

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +Go에서는 변수를 부울 타입으로 정의하기 위해 `bool`을 사용합니다. 값은 `true` 또는 `false` 만 가능하고 `false`가 기본값입니다. ( ***여러분은 변수의 타입을 숫자에서 부울로 부울에서 숫자로 변환 할 수 없습니다.*** )
변수를 부울 타입으로 정의하기 위해 `bool`을 사용합니다. > 부울 타입의 변수를 정의하기 위해 `bool`을 사용합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +    valid := false      // 변수를 정의할 때 간략한 구문 사용
변수의 간략한 선언

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +### 수 타입
숫자 타입

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +정수형 타입(Integer type)에는 부호있는 정수 타입과 부호없는 정수 타입이 모두 포함됩니다. Go는 `int`와 `uint`를 동시에 가지며 길이는 같지만 운영체제에 따라 길이가 다릅니다. 32 비트 운영 체제에서는 32 비트를, 64 비트 운영 체제에서는 64 비트를 사용합니다. Go는 또한 `rune`, `int8`, `int16`, `int
정수형 타입 (Integer type)

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +정수형 타입(Integer type)에는 부호있는 정수 타입과 부호없는 정수 타입이 모두 포함됩니다. Go는 `int`와 `uint`를 동시에 가지며 길이는 같지만 운영체제에 따라 길이가 다릅니다. 32 비트 운영 체제에서는 32 비트를, 64 비트 운영 체제에서는 64 비트를 사용합니다. Go는 또한 `rune`, `int8`, `int16`, `int
운영체제에 따라 길이가 다릅니다. > 특정 길이는 운영체제에 따라 다릅니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +정수형 타입(Integer type)에는 부호있는 정수 타입과 부호없는 정수 타입이 모두 포함됩니다. Go는 `int`와 `uint`를 동시에 가지며 길이는 같지만 운영체제에 따라 길이가 다릅니다. 32 비트 운영 체제에서는 32 비트를, 64 비트 운영 체제에서는 64 비트를 사용합니다. Go는 또한 `rune`, `int8`, `int16`, `int
별명 > 별칭

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +> `make` 0이 아닌 값을 반환합니다.
`make`는 0이 아닌 값을 반환합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +0 값은 빈 값을 의미하지 않습니다. 대부분의 경우 변수가 기본값으로 사용합니다. 다음은 일부 영 (zero) 값 목록입니다.
0 값 > 제로값

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +0 값은 빈 값을 의미하지 않습니다. 대부분의 경우 변수가 기본값으로 사용합니다. 다음은 일부 영 (zero) 값 목록입니다.
대부분의 경우 변수가 기본값으로 사용합니다. > 이는 대부분의 경우 변수가 기본값으로 사용하는 값입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +0 값은 빈 값을 의미하지 않습니다. 대부분의 경우 변수가 기본값으로 사용합니다. 다음은 일부 영 (zero) 값 목록입니다.
영 (zero) 값 > 제로값

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +> `new` 포인터를 반환합니다.
`new`는 포인터를 반환합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +한 가지 중요한 점은 이러한 타입간에 값을 할당 할 수 없다는 사실을 알아야합니다. 이러한 연산은 컴파일 오류를 발생시킵니다.
이러한 타입간에 값을 할당 할 수 없다는 사실을 알아야합니다. > 이들 타입간 할당은 불가능하다는 것을 알아야합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +한 가지 중요한 점은 이러한 타입간에 값을 할당 할 수 없다는 사실을 알아야합니다. 이러한 연산은 컴파일 오류를 발생시킵니다.
이러한 연산은 컴파일 오류를 발생시킵니다. > 다음 연산은 컴파일 오류를 발생시킵니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +비록, `int32`의 길이가 `int8`보다 길고 `int` 타입과 동일하지만 그 타입간에 값을 할당 할 수는 없습니다. ( ***만약 c라면 여기에는 int 타입으로 선언 될 것입니다.*** )
`int32`가 `int8`보다 긴 길이를 갖고 int와 동일한 타입을 가지지만, 이들간의 값 할당은 불가능합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +비록, `int32`의 길이가 `int8`보다 길고 `int` 타입과 동일하지만 그 타입간에 값을 할당 할 수는 없습니다. ( ***만약 c라면 여기에는 int 타입으로 선언 될 것입니다.*** )
위에서 c는 `int`형으로 단언됩니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +실수형 타입(Float type)은 `float32`와 `float64`타입을 가지고 있고 `float`타입은 없습니다. 만약 간결한 구문을 사용할 경우 기본적으로 `float64`가 기본 타입이됩니다.
실수형 타입 (Float type)

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +실수형 타입(Float type)은 `float32`와 `float64`타입을 가지고 있고 `float`타입은 없습니다. 만약 간결한 구문을 사용할 경우 기본적으로 `float64`가 기본 타입이됩니다.
`float32`와 `float64`타입을 가지고 있고 `float`타입은 없습니다. > `float32`와 `float64`의 타입을 가지며 `float`라는 타입은 없습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +실수형 타입(Float type)은 `float32`와 `float64`타입을 가지고 있고 `float`타입은 없습니다. 만약 간결한 구문을 사용할 경우 기본적으로 `float64`가 기본 타입이됩니다.
만약 간결한 구문을 사용할 경우 기본적으로 `float64`가 기본 타입이됩니다. > 간결한 구문을 사용할 경우 후자가 기본 타입으로 사용됩니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +이게 다가 아닙니다! Go는 복소수도 지원합니다. `complex128`(64 비트 실수와 64 비트 허수 부분을 가지고 있음)이 기본 타입입니다. 더 작은 타입이 필요하다면, `complex64`(32 비트 실수와 32 비트 허수 부분을 가짐)를 사용하세요. 형태는 `RE + IMi`이며, `RE`는 실수 부분, `IM`은 허수 부분이고, 마지막 `i`
`complex` (~~) 

괄호 전 띄어쓰기

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +이게 다가 아닙니다! Go는 복소수도 지원합니다. `complex128`(64 비트 실수와 64 비트 허수 부분을 가지고 있음)이 기본 타입입니다. 더 작은 타입이 필요하다면, `complex64`(32 비트 실수와 32 비트 허수 부분을 가짐)를 사용하세요. 형태는 `RE + IMi`이며, `RE`는 실수 부분, `IM`은 허수 부분이고, 마지막 `i`
형태는 `RE + IMi`이며, `RE`는 실수 부분, `IM`은 허수 부분이고, 마지막 `i`는 허수입니다. > 이 타입의 형태는 `RE + IMi`이고 `RE`는 실수 부분, `IM`은 허수 부분이며 마지막 `i`는 허수입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +앞 장에서 언급 한 바와 같이 Go 문자열은 모두`UTF-8` 코드가 채용되고 있습니다. 문자열은 쌍 따옴표 (` ""`) 또는 백틱 (``` `` ```)로 둘러싸인되는 것으로 정의하며 타입은 `string`입니다.
앞 장에서 언급 한 바와 같이 Go 문자열은 모두`UTF-8` 코드가 채용되고 있습니다. > 이 전에 Go는 UTF-8 문자열 셋을 사용한다고 했습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +앞 장에서 언급 한 바와 같이 Go 문자열은 모두`UTF-8` 코드가 채용되고 있습니다. 문자열은 쌍 따옴표 (` ""`) 또는 백틱 (``` `` ```)로 둘러싸인되는 것으로 정의하며 타입은 `string`입니다.
문자열은 쌍 따옴표 (` ""`) 또는 백틱 (``` `` ```)로 둘러싸인되는 것으로 정의하며 타입은 `string`입니다. > 문자열은 쌍 따옴표 (`""`) 또는 백틱 (``` `` ```)으로 표현됩니다

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +문자열 값을 인덱스로 변경하는 것은 불가능합니다. 다음 코드를 컴파일 할 때 오류가 발생합니다.
다음 코드를 컴파일 할 때 오류가 발생합니다. > 다음 코드는 컴파일시 오류를 발생시킵니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +Go는 에러 메시지를 다루기 위해 하나의 `error` 타입을 가지고 있습니다. 오류를 처리하는`errors` 패키지도 있습니다.
오류를 처리하는`errors` 패키지도 있습니다. > 에러를 처리하기 위한 `errors` 패키지 또한 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +만약 여러분이 여러개의 상수, 변수, 혹은 패키지를 임포트 하고싶다면, 그룹 형식을 사용할 수 있습니다.
변수, 혹은 > 변수 혹은

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +상수 `iota`의 값을 지정하지 않으면 `const ()` 그룹의 상수 값의 첫 번째 값은 `0`이됩니다. 상수가 명시 적으로 값을 지정하지 않으면 그 값은 마지막 값과 동일하게 할당됩니다. 마지막 상수의 값이 `iota`이면 할당되지 않은 상수 값은 `iota`입니다.
`const ()` 그룹의 상수 값의 첫 번째 값은 > `const ()` 그룹의 첫 번째 상수값은

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +상수 `iota`의 값을 지정하지 않으면 `const ()` 그룹의 상수 값의 첫 번째 값은 `0`이됩니다. 상수가 명시 적으로 값을 지정하지 않으면 그 값은 마지막 값과 동일하게 할당됩니다. 마지막 상수의 값이 `iota`이면 할당되지 않은 상수 값은 `iota`입니다.
뒤에 따라오는 상수들에 명시적으로 값을 할당하지 않으면, 마지막값과 동일한 값을 갖게됩니다. 만약 마지막 상수값이 `iota`라면, 그 이후의 할당 되지않은 상수값들 또한 `iota`를 값으로 갖습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +Go는 `iota`라는 키워드가 있습니다. 이 키워드는 `enum`을 선언 할 때 사용됩니다. 이 기본값은 0부터 시작하며 순차적 1이 추가됩니다 :
Go에는 `iota`라는 키워드가 있으며, 이는 `enum`을 생성할 때 사용됩니다. 이는 `0`부터 시작해 `1`씩 증가합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +    w  // 상수 이름 다음에 표현식이 없으면 마지막 표현식을 사용합니다.
상수 이름 > 상수명

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +    // 그래서 암시 적으로 w = iota를 말하고 있습니다. 따라서 w == 3이고, y와 z는 모두 "= iota"를 생략 할 수 있습니다.
즉 암시적으로 w = iota를 뜻합니다. 따라서 w == 3이며 y와 z 또한 "= iota"를 생략할 수 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +const v = iota // iota가 `const` 키워드를 다시 만난다면, iota가 `0`로 초기화됩니다. 그러므로 v = 0입니다.
iota가 `const` 키워드를 만나면, `0`으로 초기화되므로, v = 0입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +  e, f, g = iota, iota, iota //  iota의 값은 한 행에서 동일하므로 e=0, f=0, g=0
iota는 한 라인에서 같은 값을 가지므로 e=0, f=0, g=0입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +Go는 몇몇 기본 동작이 있기 때문에 간결합니다.
Go가 간결한 이유는 다음과 같은 기본적인 동작을 가지고 있기 때문입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- 대문자로 시작하는 변수는 해당 변수를 외부에서도 쓸 것임을 의미합니다.
대문자로 시작하는 모든 변수는 외부에 노출됨을 의미하며, 그 외의 경우는 프라이빗 변수입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- 동일한 규칙이 함수와 상수에 적용되며 `public`또는 `private` 키워드가 Go에는 없습니다.
함수와 상수에도 동일한 규칙이 적용되며, Go에는 `public` 또는 `private` 키워드가 존재하지 않습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`array`는 배열입니다. 우리는 다음과 같이 정의합니다.
우리는 다음과 같이 정의합니다. > 다음과 같이 정의합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`[n] type`에서 `n`은 배열의 길이이고 `type`은 내부 요소의 타입입니다. 다른 언어들처럼, 우리는 `[]`를 사용하여 배열 내에서 요소 값을 가져 오거나 설정합니다.
`[n] type` > `[n]type`

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`[n] type`에서 `n`은 배열의 길이이고 `type`은 내부 요소의 타입입니다. 다른 언어들처럼, 우리는 `[]`를 사용하여 배열 내에서 요소 값을 가져 오거나 설정합니다.
`type`은 내부 요소의 타입입니다. > `type`은 원소의 타입입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`[n] type`에서 `n`은 배열의 길이이고 `type`은 내부 요소의 타입입니다. 다른 언어들처럼, 우리는 `[]`를 사용하여 배열 내에서 요소 값을 가져 오거나 설정합니다.
요소 > 원소

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`[n] type`에서 `n`은 배열의 길이이고 `type`은 내부 요소의 타입입니다. 다른 언어들처럼, 우리는 `[]`를 사용하여 배열 내에서 요소 값을 가져 오거나 설정합니다.
다른 언어들처럼, 우리는 `[]`를 사용하여 배열 내에서 요소 값을 가져 오거나 설정합니다. > 다른 언어에서와 같이, 배열의 원소값을 가져오거나 설정하기 위해 `[]`를 사용합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +var arr [10]int  // arr은 [10]int 타입 배열
[10]int 타입의 배열

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +arr[1] = 13      // 요소에 값을 할당합니다.
요소 > 원소

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 요소 값 42를 반환합니다.
원소값 42를 반환합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 이 배열의 10 번째 요소의 기본값을 반환하며 값은 0입니다.
10 번째 요소의 > 10번째 원소의

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +length는 배열 타입의 일부이기 때문에 `[3]int`와 `[4]int`는 다른 타입이므로 배열의 길이를 변경할 수 없습니다. 배열을 인수로 사용하면 함수는 레퍼런스 대신 복사본(copy)을 가져옵니다! 레퍼런스를 사용하려면 `slice`를 사용하는 것이 좋고 나중에 이 내용을 다룹니다.
`[3]int`와 `[4]int`는 다른 타입이므로 배열의 길이를 변경할 수 없습니다. > `[3]int`와 `[4]int`는 다른 타입이며, 배열의 길이는 변경할 수 없습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +length는 배열 타입의 일부이기 때문에 `[3]int`와 `[4]int`는 다른 타입이므로 배열의 길이를 변경할 수 없습니다. 배열을 인수로 사용하면 함수는 레퍼런스 대신 복사본(copy)을 가져옵니다! 레퍼런스를 사용하려면 `slice`를 사용하는 것이 좋고 나중에 이 내용을 다룹니다.
레퍼런스를 사용하려면 `slice`를 사용하는 것이 좋고 나중에 이 내용을 다룹니다. > 레퍼런스를 사용하기 위해선 `slice`를 사용하는 것이 좋습니다. 이는 나중에 살펴보겠습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +배열을 정의 할 때`: =`를 사용할 수 있습니다.
할 때`: =`를 > 할 때 `: =`를

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +a := [3]int{1, 2, 3} // 3개의 원소로 구성된 int 배열을 선언
3개의 원소로 구성된 int형 배열을 정의

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 첫 요소부터 3번째 요소까지 값이 할당된 길이가 총 10인 int 배열을 선언합니다.
첫 세 개의 원소에 값을 할당한 길이가 10인 int형 배열을 선언합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 첫 요소부터 3번쨰 요소를 제외한 나머지는 기본값 0을 사용합니다.
나머지 원소들은 기본값 0을 사용합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +c := [...]int{4, 5, 6} // 길이를 미리 설정하는 대신  `...`을 사용할 수 있고 Go가 길이를 자동으로 계산합니다.
길이 매개변수로 `…`를 대신 사용하면 Go가 길이를 계산해줍니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +배열을 배열의 요소로 사용할 수 있습니다. 다음 예제를 살펴봅시다.
요소 > 원소

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +배열을 배열의 요소로 사용할 수 있습니다. 다음 예제를 살펴봅시다.
다음 예제를 살펴봅시다. > 어떻게 하는지 살펴봅시다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 이차원 배열을 하나 선언합니다. 이 배열은 두 개의 배열을 요소로하고 각 배열에는 4 개의 int 타입의 요소가 포함되어 있습니다.
요소 > 원소

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 이차원 배열을 하나 선언합니다. 이 배열은 두 개의 배열을 요소로하고 각 배열에는 4 개의 int 타입의 요소가 포함되어 있습니다.
각 배열에는 4 개의 int 타입의 요소가 포함되어 있습니다. > 각 배열은 4개의 원소를 가집니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +많은 경우에, 배열 타입은 좋은 선택이 될 수 없습니다 예를 들어 우리가 배열을 정의할 때 이 배열이 얼마만큼의 길이를 가져야 할지 모르기 때문입니다. 따라서 "동적 배열(Dynamic array)"이 필요합니다. 이것을 Go에서 `slice`라고 부릅니다.
많은 경우에, 배열 타입은 좋은 선택이 될 수 없습니다 예를 들어 우리가 배열을 정의할 때 이 배열이 얼마만큼의 길이를 가져야 할지 모르기 때문입니다. > 많은 경우, 배열 타입은 좋은 선택이 아닙니다. 예를 들어 배열을 정의할 때 이 배열이 얼마나 길어질지 알 수 없는 경우가 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +많은 경우에, 배열 타입은 좋은 선택이 될 수 없습니다 예를 들어 우리가 배열을 정의할 때 이 배열이 얼마만큼의 길이를 가져야 할지 모르기 때문입니다. 따라서 "동적 배열(Dynamic array)"이 필요합니다. 이것을 Go에서 `slice`라고 부릅니다.
이것을 Go에서 > 이것을 Go에선

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`slice`는 실제로 동적 배열이 아닙니다. 레퍼런스 타입입니다. `slice`는 선언이 `array`와 비슷하지만 길이가 필요없는 기본 `array`를 가리킵니다.
`slice`는 `array`와 비슷한 선언을 갖는 기본 `array`를 가리키지만 길이가 필요없습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`slice`는 기존 슬라이스 나 배열을 재정의 할 수 있습니다. `slice`는 슬라이스 할 때 `array[i:j]`를 사용합니다. 여기서`i`는 시작 인덱스이고 `j`는 끝 인덱스입니다. 그러나 `array[j]`는 슬라이스의 길이 때문에 슬라이스되지 않습니다. 길이는 `j-i`입니다.
슬라이스 나 > 슬라이스나

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 'a'는 배열 ar에서 3 ~ 5 번째 원소를 가리 킵니다.
ar에서 > ar의

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 'a'는 배열 ar에서 3 ~ 5 번째 원소를 가리 킵니다.
가리 킵니다. > 가리킵니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`slice`와 배열은 선언시에 구분되므로 주의하세요. 배열을 선언 할 때 괄호 안에 배열의 길이를 명시하거나 `...`을 사용해 자동으로 길이를 계산합니다. 그러나 `slice`를 선언 할 때는 중괄호에 문자가 없습니다.
`slice`와 `array` 정의간의 차이점에 주목하세요. Go가 길이를 계산해줄 때에는 `[…]`를 사용하지만, 슬라이스만 정의할 때에는 `[]`를 사용합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +기본 데이터 구조:
배열과 슬라이스의 기본 데이터 구조

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +슬라이스에는 몇 가지 편리한 용법이 있습니다.
슬라이스에는 몇 가지 편리한 연산들이 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `slice`는 0 기반이고, `ar[:n]`은 `ar[0:n]`과 같습니다.
`slice`는 0 기반이고 > `slice`는 인덱스가 0부터 시작하며

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `slice`의 두 번째 인덱스가 생략되면 슬라이스의 길이를 자동으로 넣어줍니다. `ar[n:]`은 `ar[n:len(ar)]`과 같습니다.
두 번째 인덱스가 생략되어 있으면 `slice`의 길이를 대신 사용합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `ar[:]`을 사용하여 전체 배열을 의미합니다. 이유는 위 두 문장에서 알 수 있습니다.
전체 배열을 슬라이스 하기위해 `ar[:]`를 사용할 수 있으며, 원리는 위 두 문장에서 알 수 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`slice`에 관한 더 많은 예제들.
`slice` 관련 추가 예제들

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 편리한 용법들
편리한 연산들

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +aSlice = array[3:7]  // aSlice는 d,e,f,g를 요소로 갖고，len=4，cap=7가 됩니다.
cap=7가 > cap=7이

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +aSlice = array[3:7]  // aSlice는 d,e,f,g를 요소로 갖고，len=4，cap=7가 됩니다.
요소 > 원소

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +bSlice = aSlice[1:3] // bSlice는 aSlice[1], aSlice[2]를 가지고 있으므로 요소 e,f를 가지고 있는 것이 됩니다.
bSlice는 aSlice[1], aSlice[2]를 포함하므로, 원소 e, f를 갖습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +bSlice = aSlice[:3]  // bSlice는 aSlice[0], aSlice[1], aSlice[2]를 가지고 있으므로 요소 d,e,f를 가지고 있는 것이 됩니다.
bSlice는 aSlice[0], aSlice[1], aSlice[2]를 포함하므로 원소 d,e,f를 갖습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +bSlice = aSlice[0:5] // 슬라이스가 cap의 범위내에서 확장 될 수 있습니다. 이제 bSlice에는 d, e, f, g, h가 포함됩니다.
슬라이스가 > 슬라이스는

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +bSlice = aSlice[0:5] // 슬라이스가 cap의 범위내에서 확장 될 수 있습니다. 이제 bSlice에는 d, e, f, g, h가 포함됩니다.
이제 bSlice에는 d, e, f, g, h가 포함됩니다. > 이제 bSlice는 d,e,f,g,h를 포함합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +bSlice = aSlice[:]   // bSlice 이제 aSlice와 같은 요소인 d,e,f,g를 가지게됩니다.
bSlice는 aSlice와 동일한 원소들인 d,e,f,g를 갖습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +슬라이스에 대한 몇 가지 내장 함수가 있습니다.
슬라이스를 위한 몇 가지 내장 함수들이 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `copy`는 하나의 슬라이스에서 다른 슬라이스로 요소를 복사하고 복사 된 요소의 수를 반환합니다.
요소 > 원소

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `copy`는 하나의 슬라이스에서 다른 슬라이스로 요소를 복사하고 복사 된 요소의 수를 반환합니다.
복사 된 > 복사된

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`slice`는 레퍼런스 타입이므로 어떤 변경도 같은 슬라이스나 배열을 가리키는 다른 변수에 영향을 미칩니다.
어떤 변경도 > 변경시

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +예를 들어 위의 `aSlice`나 `bSlice`의 경우 `aSlice`에서 요소의 값을 변경하면 `bSlice`도 변경됩니다.
`aSlice`에서 요소의 값을 변경하면 > `aSlice`에서 원소값을 변경하면

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +개념적으로는 `slice`는 구조입니다. 이 구조체에는 3 개의 요소가 포함되어 있습니다:
`slice`는 정의에 의한 구조체와 같으며 다음의 3 부분을 포함하고 있습니다:

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- 하나는 포인터입니다. 배열 중의 `slice`가 나타내는 시작 위치를 가리킵니다.
`slice`의 시작 지점을 가리키는 포인터

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `slice`의 길이입니다.
`slice`의 길이

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- 나머지 하나는 용량(Capacity)입니다, 시작 인덱스에서 슬라이스의 끝 인덱스까지의 길이를 나타냅니다.
`slice`의 시작 인덱스부터 끝 인덱스까지의 길이를 나타내는 용량 (Capacity)

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +또한, 슬라이스 (`(cap-len) == 0`)를 위한 길이가 충분하지 않으면, `append`는 이 슬라이스에 대한 새로운 배열을 반환합니다.
또한, 슬라이스의 길이가 충분하지 않은 경우 (`(cap-len) == 0`), `append`는 이 슬라이스의 새로운 배열을 반환합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +이 경우 이전 배열을 가리키는 다른 슬라이스가 영향을 받지 않습니다.
다른 슬라이스가 > 다른 슬라이스는

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`map`은 파이썬에서 딕셔너리처럼 동작합니다. 맵을 정의할 땐 `map[keyType]valueType` 형식을 사용하세요.
`map`은 파이썬에서의 딕셔너리와 유사하게 동작합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +몇 가지 코드를 살펴 보겠습니다. `map`의 `set`과 `get` 값은 `slice`와 비슷하지만 차이점이 있습니다. `slice`의 인덱스는 무조건 `int`타입인 반면에 `map`은 그 이상을 사용할 수 있습니다 : 예를 들어 `int`,`string` 또는 원하는 것을 선택해 사용할 수 있고. 또한 `==`와 `!=`를 사용하여 값을 비교할 수
`map`의 `set`과 `get` 값은 `slice`와 비슷하지만 차이점이 있습니다. `slice`의 인덱스는 무조건 `int`타입인 반면에 `map`은 그 이상을 사용할 수 있습니다 : 예를 들어 `int`,`string` 또는 원하는 것을 선택해 사용할 수 있고. > `map`의 `set`과 `get`은 `slice`와 유사하지만 `slice`의 인덱스는 무조건 `int` 타입인 반면에 `map`은 그 이상을 사용할 수 있습니다: 예를 들어 `int`,`string` 또는 여러분의 원하는 그 어떤것도 사용할 수 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +몇 가지 코드를 살펴 보겠습니다. `map`의 `set`과 `get` 값은 `slice`와 비슷하지만 차이점이 있습니다. `slice`의 인덱스는 무조건 `int`타입인 반면에 `map`은 그 이상을 사용할 수 있습니다 : 예를 들어 `int`,`string` 또는 원하는 것을 선택해 사용할 수 있고. 또한 `==`와 `!=`를 사용하여 값을 비교할 수
또한 `==`와 `!=`를 사용하여 값을 비교할 수 있습니다. > 또한 값을 비교하기 위해 `==`와 `!=`를 사용할 수 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 문자열을 key의 타입으로 사용하고, int를 값의 타입으로 사용하고, `make`를 사용하여 초기화합니다.
key 타입으로 문자열을, 값 타입으로 int를 사용하고, 'make'로 초기화를 합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `map`은 순서가 보장이안됩니다. `map`을 출력 할 때마다 다른 결과를 얻습니다. `index`로 값을 얻는 것은 불가능하고, `key`를 사용해서 얻을 수 있습니다.
`map`에는 순서가 없습니다. `map`은 출력 할 때마다 다른 결과를 얻습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `map`은 순서가 보장이안됩니다. `map`을 출력 할 때마다 다른 결과를 얻습니다. `index`로 값을 얻는 것은 불가능하고, `key`를 사용해서 얻을 수 있습니다.
`index`로 값을 얻는 것은 불가능하고, `key`를 사용해서 얻을 수 있습니다. > `index`로 값을 얻는 것은 불가능하며 `key`를 사용해야만 합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `len`도 `map`에서 동작합니다. `len`은 map이 얼마나 많은 `key`를 가지고 있는지 반환합니다.
`len`은 map이 얼마나 많은 `key`를 가지고 있는지 반환합니다. > `len`은 map이 가지고 있는 `key`의 갯수를 반환합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +- `map`을 통해 값을 변경하는 것은 아주 쉽습니다. 단순히 `numbers["one"] = 11`을 사용하여 `key`의 값을 `11`으로 변경하세요.
단순히 `numbers["one"] = 11`을 사용하여 `key`의 값을 `11`으로 변경하세요. > one `key`의 값을 `11`로 변경하기 위해 단순히 `numbers["one"]=11`를 사용합니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`key:val` 형식을 사용하여 맵의 값을 초기화 할 수 있으며 `map`에는 `key`가 있는지 확인하는 내장 메소드가 있습니다.
`map`에는 `key`가 있는지 확인하는 내장 메소드가 있습니다. > `map`은 `key`의 존재 여부를 확인할 수 있는 내장 메서드를 가지고 있습니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// map에는 두 개의 반환 값이 있습니다. 두 번째 반환 값에 대해 키가 존재하지 않으면
반환 값 > 반환값

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +// 'ok'는 false를 반환합니다. 그렇지 않으면 true를 리턴합니다.
리턴 > 반환

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +delete(rating, "C")  // key "c"가 있는 요소 삭제
"c" 키값을 가진 원소 삭제

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +위에서 말했듯이 `map`은 레퍼런스 타입입니다. 만약 두 개의 `map`이 동일한 기본 데이터를 가리키면, 어떤 변화라도 양쪽 모두에 영향을 미칩니다.
어떤 변화라도 양쪽 모두에 영향을 미칩니다. > 변화가 생기면 양쪽 모두에 영향을 미칩니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +m1["Hello"] = "Salut"  // 이제 m["hello"] 의 값은 Salut입니다.
m["hello"] 의 > m["Hello"]의

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`make`는 `map`, `slice`, `channel`과 같은 내장 모델에 대한 메모리 할당을 수행하는 반면, `new`는 타입의 메모리 할당을위한 것입니다.
`new`는 타입의 메모리 할당을위한 것입니다. > `new`는 타입 메모리 할당을 위한 것입니다.

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`new(T)`는 타입 `T`의 메모리에 0 값을 할당하고, 메모리 주소를 반환합니다. 메모리 주소는 `*T` 타입의 값입니다. Go의 정의에 따라 포인터는 `T`의 0 값을 가리키는 포인터를 반환합니다.
0 값 > 제로값

2017-03-06 17:41 UTC, mingrammer commented on ko/02.2.md
> +`new(T)`는 타입 `T`의 메모리에 0 값을 할당하고, 메모리 주소를 반환합니다. 메모리 주소는 `*T` 타입의 값입니다. Go의 정의에 따라 포인터는 `T`의 0 값을 가리키는 포인터를 반환합니다.
Go의 정의에 의해, 이는 `T`의 제로값을 가리키는 포인터를 반환합니다.

2017-03-07 02:24 UTC, qkraudghgh commented
@mingrammer
Check it plz

2017-03-07 06:27 UTC, mingrammer approved these changes

2017-03-07 06:29 UTC, merged